### ISSUE TITLE
Issue with encoding

### ISSUE THREAD

**Issue by jevm** [ailjushkin/robotframework-reportportal-ng#7]
Hi,
I am constantly getting this, on one or another test case

`[ ERROR ] Calling method 'start_keyword' of listener 'reportportal_listener' failed: UnicodeEncodeError: 'ascii' codec can't encode character u'\u263a' in position 817: ordinal not in range(128)`

What could be the reason?

After this error appears, all further activity and calling all methods goes with it, suite remains unfinished in ReportPortal.

**Comment by skhomuti** [comment]
Hi @jevm, you use python 3 or python 2?

**Comment by jevm** [comment]
@skhomuti python 2.7.2.1 portable

**Comment by skhomuti** [comment]
For python27 need fix, but when used python 3*  such an error should not occur
This can happen if there are Cyrillic symbols in the name, documentation or arguments of the keyword

**Comment by jevm** [comment]
With Python 3 I am getting another kind of error:

```
[ ERROR ] Calling method 'start_keyword' of listener 'reportportal_listener' failed: ResponseError: Invalid response: Expecting value: line 1 column 1 (char 0): <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"

        href="./img/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">

    <title>Report Portal - Page 404</title>
</head>
```

**Comment by ailjushkin** [comment]
@jevm There are several options for this error:

* Wrong `RP_ENDPOINT`. Example: `--variable RP_ENDPOINT:http://reportportal.local:8080`
* Not all components are up and running. Please go to your terminal and look there for their status: `docker ps -a`. It should be `Up`, not `Starting` or `Exited`

**Comment by jevm** [comment]
@ailjushkin Thanks for your response, the first one is definitely not the case as I am using it for quite a while. 

Well, I did try polling the docker, everything seems to be running. But I am temporarily under Windows7 and Docker toolbox, so maybe there could be issues due to this setup?

**Comment by ailjushkin** [comment]
@jevm well, If you say that you are running the instance of RP locally, on windows 7 and you can log into the UI through the localhost:8080, unfortunately the only option is:

* Run your test with listener under Debugger and point out context of the error
* You can also get a tcp or http dump to look what kind of request was sent to the server and then come with some specific results.

**Comment by jevm** [comment]
@ailjushkin 
Thank you for your comments. Now I have a RP instance running on a normal remote Linux machine and after several executions issues didn't emerge again. So I suspect it is related to running on Windows-based system and maybe some performance/stability issues.

A little bit offtopic - did you ever try to run your listener with pabot for parallel execution? In my setup it doesn't work at all, I've already tried every solution I came up with.

**Comment by ailjushkin** [comment]
@jevm sure, we use pabot for test executions, this issue related to the documentation of this package.
look here: https://github.com/ailjushkin/robotframework-reportportal-ng/blob/master/reportportal_listener/__init__.py#L34

as you can see, when you attach this listener , you can pass launch_id parameter to it, like:

```
pabot --listener reportportal_listener:<launch_id>
```

Where <launch_id> is some hash which you get when creating launch manually using RP API.
Did I give enough clarification by your question?

**Comment by jevm** [comment]
@ailjushkin where could I take this parameter from? In my case cmdline looks like: 

`pabot --verbose --processes 2 --command --listener reportportal_listener --end_command --variable RP_UUID:eb84a7c5-d56f-4bdc-a78a-cdde8be19555 --variable RP_ENDPOINT:http://192.168.11.121:8080 --variable RP_LAUNCH:nbsf_tester_TEST_EXAMPLE --variable RP_PROJECT:nf_test --outputdir Reports --includeSMOKE RobotTests`

Is this one of these parameters or is it something custom?

**Comment by ailjushkin** [comment]
@jevm yes, its not included because of the pabot itself. it doesn't support normal multithreading

**Comment by ailjushkin** [comment]
@jevm If we're done here, can I close this issue?

**Comment by jevm** [comment]
@ailjushkin Yes sure, thank you for your help. Just the last thing to mention: do I understand it correctly that test results from all test suites will be fetched into a single test launch instance which will be created by this external script?

**Comment by ailjushkin** [comment]
@jevm yes, you create launch from the external script and everything what pabot executes, each parallel 
suite should be recorded into this one launch
