### ISSUE TITLE
Execution details not available in Reportportal when tests are run in parallel mode using pabot

### ISSUE THREAD

**Issue by amalsgit** [ailjushkin/robotframework-reportportal-ng#8]
When I execute parallel tests in robot framework using the pabot lib, no data is captured in reportportal.
Execution command: 
`pabot --processes 2 -d results -i Smoke --listener reportportal_listener --escape quot:Q --variable RP_ENDPOINT:http://192.168.99.100:8080 --variable RP_UUID:531345ef-2c3a-4b28-8472-dbce263d4ca7 --variable RP_LAUNCH:"Demo Tests" --variable RP_PROJECT:fileflipper --loglevel DEBUG tests`

I am attaching the generated output.xml.
[output.zip](https://github.com/ailjushkin/robotframework-reportportal-ng/files/1910031/output.zip)

**Comment by ailjushkin** [comment]
This is because you did not provide a launch id. I will fix readme and write you back.

**Comment by ailjushkin** [comment]
Updated Readme: 

https://github.com/ailjushkin/robotframework-reportportal-ng/blob/master/README.rst#example
