### ISSUE TITLE
Extend launch id usage to non-pabot cases and enable reporting reruns

### ISSUE THREAD

**Issue by Koili** [ailjushkin/robotframework-reportportal-ng#9]
Hi,

Thanks for the work on the listener. I have two feature requests:

1)
Would it be possible to extend the usage of launch_id for all times it is given to the listener as argument? At the moment launch_id is ignored if pabot is not also used. I think it would be logical to use a certain launch if it was so defined in listener variables.

This would require changing __init__.py:
line 103 to: 
`if self._launch_id is not None`
the following pabot raise exception could be moved to the "else" clause in line 109.

line 136 to:
`if self._launch_id is None`

These changes would enable the user to specify a certain launch for his run, whether or not he wants to use pabot.

2)
Do you think it would be possible to support reporting rerunning the cases in robot with --rerunfailed?
I was thinking something along the lines that if a parameter --RP_RERUN was given with launch_id, the listener would try to find an existing test case with same name in the launch and update that test cases status, instead of creating a new testcase inside the launch.

Thanks

**Comment by ailjushkin** [comment]
> Do you think it would be possible to support reporting rerunning the cases in robot with --rerunfailed?
> I was thinking something along the lines that if a parameter --RP_RERUN was given with launch_id, the listener would try to find an existing test case with same name in the launch and update that test cases status, instead of creating a new testcase inside the launch.

I think that this is just improper way of using the Report Portal, you don't want to write results in the old launch and update its test cases, it is just wrong.

Report Portal's goal is in tracing the results of autotests within a continuous integration process. Your tests should be reported automatically, for instance, by Jenkins and send results from some build, regularly.
Every single build of your automated tests in Jenkins is a launch in Report Portal.

**Comment by Koili** [comment]
Yeah, I agree. You are right.

How about the first request - respecting the launch ID given at the listener initialization. I  believe it is a good improvement.

**Comment by ailjushkin** [comment]
@Koili Sounds good to me

**Comment by ailjushkin** [comment]
@Koili Could you please make a PR? Seems like you have already investigated the correct solution. Then we could push the new version on pypi.

**Comment by Koili** [comment]
Sure, but I cant do it until tuesday - if you want to do it earlier it is just changing the check for use_pybot to if _launch_id exists in the two places it is used.

Cheers
--
K

**Comment by ailjushkin** [comment]
#12
